### ISSUE TITLE
문의 드립니다.

### ISSUE THREAD

**Issue by junghan0611** [depromeet/algoStudy#64]
너무 좋은 스터디를 진행 중이시네요.
혹시 문제를 고르시는 기준이 있나요?

어떤 목적으로 진행을 하시는지 궁금합니다.

**Comment by wkdtjsgur100** [comment]
안녕하세요. 일단 저희 스터디를 좋게 봐주셔서 감사합니다 :)
문제는 하루에 hackerrank라는 사이트에서 easy, medium, hard 난이도를 선택할 수 있는데 그 중에서 매일 easy, medium 한 문제씩 골라서 출제하고 있구요, 세부적인 기준은 medium 중에서 정답률이 현저하게 낮지 않은 문제/획득 점수가 너무 높지 않은 문제를 기준으로 내고 있습니다.
저희 스터디의 목적은 문제해결역량을 키우기 위해 알고리즘 푸는 습관을 들이자는 것이 주 목적입니다 ㅎㅎ

**Comment by junghan0611** [comment]
빠른 답변 감사합니다. 👍  

하나 더 질문드리자면 문제 풀이하고 나서 확인 혹은 세미나는 어떻게 진행하시나요?

푸는 것도 중요하지만 알고리즘을 서로 설명하고 더 나은 방안을 고민하는 시간도 의미있다고 보는데요. 
언제, 얼마나, 어떤 방식으로 진행하시는지 궁금합니다.

**Comment by wkdtjsgur100** [comment]
문제 풀이는 토요일 오후에 1시간 정도 짧게 리뷰하구요, 말씀하신 그대로 서로 풀었던 풀이 방법들을 공유하고 더 나은 방법이 있을 지 고민하는 시간을 가집니다. 
리뷰가 끝난 이후에는 약 1~2시간 정도 google kickstart 같은 대회의 문제를 다함께 풀어보는 시간도 가지고 있습니다!
